name: PlatformIO CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example: [./examples/Basic/Basic.ino, ./examples/14BitMode/14BitMode.ino, ./examples/UnlatchedInterrupt/UnlatchedInterrupt.ino]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build examples
        run: pio ci --lib=./ --board=d1_mini_pro --board=uno --board=adafruit_trinket_m0
        env:
          PLATFORMIO_CI_SRC: ${{ matrix.example }}

  clang-format-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: RafikFarhad/clang-format-github-action@v3
        with:
          sources: "src/*, examples/*"
          style: file
